name: Auto Push

on:
  push:
    branches:
      - main # Replace with the name of the branch to monitor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - run: npm install
      - run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "NetlinkApp"
          git config --global user.email "app@netlink.vn"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Auto commit by GitHub Actions"
          git push
